### ISSUE TITLE
Yosemite build fails on NSTextContainer.size

### ISSUE THREAD

**Issue by fricklerhandwerk** [gbrueckner/Snapp#8]
Trying to build on 10.10.5 I get

```
src/SNTextView.m:29:24: error: property 'size' not found on object of type 'NSTextContainer *'
    self.textContainer.size = self.maxSize;
                       ^
```

Commenting the line out lets the build pass and the thing appears to work, but I guess this is not a very smart thing to do. Unfortunately I have no idea about the OS X API, so I can't provide a suggestion to solve this.
